

INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO PRESIDENCIA DE ESTACA','2022/01/05','19:30','ESTACA','PRESIDENCIA DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO SUMO CONSELHO','2022/01/09','06:30','ESTACA','PRESIDENCIA DA ESTACA E SUMO CONSELHO');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','CONSELHO DE BISPOS','2022/01/16','18:00','ESTACA','PRESIDENCIA DA ESTACA E BISPADOS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO PRESIDENCIA DE ESTACA','2022/01/19','19:30','ESTACA','PRESIDENCIA DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ORM','SEMANA DA PALAVRA DE SABEDORIA','2022/01/20','16:00','ESTACA','JOVENS E LIDERES');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ORM','SEMANA DA PALAVRA DE SABEDORIA','2022/01/21','16:00','ESTACA','JOVENS E LIDERES');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ORM','SEMANA DA PALAVRA DE SABEDORIA','2022/01/22','16:00','ESTACA','JOVENS E LIDERES');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO SUMO CONSELHO','2022/01/23','06:30','ESTACA','PRESIDENCIA DA ESTACA E SUMO CONSELHO');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','CONSELHO DE ESTACA','2022/01/23','18:00','ESTACA','PRESIDENCIA DA ESTACA E LIDERES DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO PRESIDENCIA DE ESTACA','2022/02/02','19:30','ESTACA','PRESIDENCIA DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO SUMO CONSELHO','2022/02/06','06:30','ESTACA','PRESIDENCIA DE ESTACA E SUMO CONSELHO');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO PRESIDENCIA DE ESTACA','2022/02/16','19:30','ESTACA','PRESIDENCIA DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO SUMO CONSELHO','2022/02/20','06:30','ESTACA','PRESIDENSIA DE ESTACA E SUMO SONSELHO');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','BEM ESTAR E AUTOSUFICIENCIA','TREINAMENTO NACIONAL DO CASE','2022/02/20','','ESTACA','TODOS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','BEM ESTAR E AUTOSUFICIENCIA','SAUDE EMOCIONAL','2022/02/22','','','TODOS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO PRESIDENCIA DE ESTACA','2022/03/02','19:30','ESTACA','PRESIDENCIA DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO SUMO CONSELHO','2022/03/06','06:30','ESTACA','PRESIDENCIA DA ESTACA E SUMO CONSELHO');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','BEM ESTAR E AUTOSUFICIENCIA','MÊS GERAÇAO DE RENDA','2022/03/08','','','');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','BEM ESTAR E AUTOSUFICIENCIA','MÊS GERAÇAO DE RENDA','2022/03/15','','','');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO PRESIDENCIA DE ESTACA','2022/03/16','19:30','ESTACA','PRESIDENCIA DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO SUMO CONSELHO','2022/03/20','06:30','ESTACA','PRESIDENCIA DA ESTACA E SUMO CONSELHO');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','MUSICA','TREINAMENTO DE REGENCIA DA ESTACA','2022/03/20','16:00','ESTACA','REGENTES');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','BEM ESTAR E AUTOSUFICIENCIA','MÊS GERAÇAO DE RENDA','2022/03/22','','','');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ORM','SABADOOH','2022/03/26',null,'ESTACA','JOVENS E LIDERES');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','CONFERENCIA ALA AEROCLUB','2022/03/27','SACRAMENTAL DA ALA','SEDE DE ESTACA','MEMBROS DA ALA E CONVIDADOS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','BEM ESTAR E AUTOSUFICIENCIA','TREINAMENTOS NACIONAL DOS ESPECIALISTAS ','2022/03/27','','','');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO PRESIDENCIA DE ESTACA','2022/03/30','19:30','ESTACA','PRESIDENCIA DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO GERAL DO SACERDOCIO',null,'','','');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO PRESIDENCIA DE ESTACA','2022/04/06','19:30','ESTACA','PRESIDENCIA DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO SUMO CONSELHO','2022/04/10','06:30','ESTACA','PRESIDENCIA DA ESTACA E SUMO CONSELHO');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','CONSELHO DE BISPOS','2022/04/17','16:00','ESTACA','PRESIDENCIA DA ESTACA E BISPOS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','HISTORIA DA FAMILIA','DEVOCIONAL HISTORIA DA FAMILIA','2022/04/17','18:00','ESTACA','TODOS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO PRESIDENCIA DE ESTACA','2022/04/20','19:30','ESTACA','PRESIDENCIA DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ORM','FESTIVAL DE HORATORIA','2022/04/23','16:00','B.BENTES','JOVENS E LIDERES');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','SOC.SOCORRO','DIA DE LAZER','2022/04/23','09:00','','LIDERES DA SOC DA ESTACA E ALAS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE SUMO CONSELHO','2022/04/24','06:30','ESTACA','PRESIDENCIA DA ESTACA E SUMO CONSELHO');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','CONSELHO DE ESTACA','2022/04/24','18:00','ESTACA','PRESIDENCIA DA ESTACA E LIDERES DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO PRESIDENCIA DE ESTACA','2022/05/04','19:30','ESTACA','PRESIDENCIA DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE SUMO CONSELHO','2022/05/08','06:30','ESTACA','PRESIDENCIA DA ESTACA E SUMO CONSELHO');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','OR','DEVOCIONAL RESTAL. DO SACERDOCIO ','2022/05/15','16:00','ESTACA','TODOS OS RAPAZES E LIDERES');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE PRESIDENCIA DE ESTA','2022/05/18','19:30','ESTACA','PRESIDENCIA DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','BEM ESTAR E AUTOSUFICIENCIA','TREINAMENTO PARA NOVOS LIDEDES','2022/05/22','','','');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE SUMO CONSELHO','2022/05/22','06:30','ESTACA','PRESIDENCIA DA ESTACA E SUMO CONSELHO');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','BEM ESTAR E AUTOSUFICIENCIA','SAUDE EMOCIONAL','2022/05/24','','','');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','CONFERENCIA CACHOEIRA','2022/05/29','SACRAMENTAL DA ALA','CAPELA CACHOEIRA','MEMBROS DA ALA E CONVIDADOS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','COMUNICAÇÃO','RESERVADO','2022/05/30','','ESTACA','TODOS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE LIDERANÇA DA ESTACA',null,null,'ESTACA','LIDERES DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DO QUORUM DE SUMO SACERDOTES',null,null,'ESTACA','SUMOS SACERDOTES DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE PRESIDENCIA DE ESTACA','2022/06/01','19:30','ESTACA','PRESIDENCIA DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE SUMO CONSELHO','2022/06/05','06:30','ESTACA','PRESIDENCIA DA ESTACA E SUMO CONSELHO');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','BEM ESTAR E AUTOSUFICIENCIA','TREINAMENTO NACIONAL DOS ESPECIALISTAS','2022/06/12','','','');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE PRESIDENCIA DE ESTACA','2022/06/15','19:30','ESTACA','PRESIDENCIA DA ESTACA ');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','CONFERENCIA DE ESTACA / LIDERENÇA DA ESTACA','2022/06/18','16:00','ESTACA','LIDERES DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','CONFERENCIA DE ESTACA / MEMBROS ADULTOS','2022/06/18','19:00','ESTACA','TODOS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','CONFERENCIA DE ESTACA / SESSÃO GERAL','2022/06/19','10:00','ESTACA','TODOS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE SUMO CONSELHO','2022/06/19','06:30','ESTACA','PRESIDENCIA DA ESTACA E SUMO CONSELHO');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ORM','SABADOOH','2022/06/25','','ESTACA','TODOS DO JOVENS E LIDERES');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','CONFERENCIA CAETES','2022/06/26','SACRAMENTAL DA ALA','CAPELA CAETES','MEMBROS DA ALA E CONVIDADOS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE PRESIDENCIA DE ESTACA','2022/06/29','19:30','ESTACA','PRESIDENCIA DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE SUMO CONSELHO','2022/07/03','06:30','ESTACA','PRESIDENCIA DA ESTACA E SUMO CONSELHO');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','BEM ESTAR AUTOSUFICIENCIA','SEMANA DA EDUCAÇAO','2022/07/05','','ESTACA','TODOS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','BEM ESTAR AUTOSUFICIENCIA','SEMANA DA EDUCAÇAO','2022/07/06','','ESTACA','TODOS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','BEM ESTAR AUTOSUFICIENCIA','SEMANA DA EDUCAÇAO','2022/07/07','','ESTACA','TODOS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','BEM ESTAR AUTOSUFICIENCIA','SEMANA DA EDUCAÇAO','2022/07/09','','ESTACA','TODOS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','OM','2022/07/09','','ESTACA','LIDERES DAS MOÇAS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE PRESIDENCIA DA ESTACA','2022/07/13','19:30','ESTACA','PRESIDENCIA DA ESTACA ');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE SUMO CONSELHO','2022/07/17','06:30','ESTACA','PRESIDENCIA DA ESTACA E SUMO CONSELHO');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','CONSELHO DE BISPOS','2022/07/17','18:00','ESTACA','PRESIDENCIA DA ESTACA E BISPADOS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','','CONFERENCIA GURGURI','2022/07/24','SACRAMENTAL DA ALA','CAPELA GURGURI','MEMBROS DA ALA E CONVIDADOS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','CONSELHO DE ESTACA','2022/07/24','18:00','ESTACA','PRESIDENCIA DA ESTACA E LIDERES DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE PRESIDENCIA DA ESTACA','2022/07/27','19:30','ESTACA','PRESIDENCIA DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE SUMO CONSELHO','2022/07/31','06:30','ESTACA','PRESIDENCIA DA ESTACA E SUMO CONSELHO');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','BEM ESTAR AUTOSUFICIENCIA','TREINAMENTO NACIONAL DO CASE','2022/08/07','','','');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE PRESIDENCIA DA ESTACA','2022/08/10','19:30','ESTACA','PRESIDENCIA DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE SUMO CONSELHO','2022/08/14','06:30','ESTACA','PRESIDENCIA DE ESTACA E SUMO CONSELHO');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','COMUNICAÇÃO','RESERVADO','2022/08/20','','','');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE PRESIDENCIA DA ESTACA','2022/08/24','19:30','ESTACA','PRESIDENCIA DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','BEM ESTAR AUTOSUFICIENCIA','MAOS QUE AJUDAM','2022/08/27','','','');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','CONFERENCIA ALA PRATAGY','2022/08/28','SACRAMENTAL DA ALA','CAPELA RATAGY','MEMBROS DA ALA E CONVIDADOS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE SUMO CONSELHO','2022/08/28','06:30','ESTACA','PRESIDENCIA DE ESTACA E SUMO CONSELHO');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE PRESIDENCIA DA ESTACA','2022/09/07','19:30','ESTACA','PRESIDENCIA DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE SUMO CONSELHO','2022/09/11','06:30','ESTACA','PRESIDENCIA DA ESTACA E SUMO CONSELHO');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','CONFERENCIA ALA B.BENTES','2022/09/11','SACRAMENTAL DA ALA','CAPELA B.BENTES','MEMBROS DA ALA E CONVIDADOS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','BEM ESTAR E AUTOSUFICIENCIA','TREINAMENTO NASCIONAL DOS ESPECIALISTAS','2022/09/18','','','');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE PRESIDENCIA DA ESTACA','2022/09/21','19:30','ESTACA','PRESIDENCIA DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','BEM ESTAR E AUTOSUFICIENCIA','SAUDE EMOCIONAL','2022/09/22','','','');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ORM','SABADOOH','2022/09/24','','ESTACA','JOVENS E LIDERES');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ORM','BAILE','2022/09/24','18:00','ESTACA','TODOS OS JOVENS E LIDERES');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','CONFERENCIA ALA TABULEIRO','2022/09/25','SACRAMENTAL DA ALA','CAPELA TABULEIRO','MEMBROS DA ALA E CONVIDADOS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE SUMO CONSELHO','2022/09/25','06:30','ESTACA','PRESIDENCIA DA ESTACA E SUMO CONSELHO');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE LIDERANÇA DO SACERDOCIO',null,null,'ESTACA','');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','ATIVIDADE DO QUORUM DE SUMO SACERDOTES',null,null,'','');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE PRESIDENCIA DE ESTACA','2022/10/05','19:30','ESTACA','PRESIDENCIA DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE SUMO CONSELHO','2022/10/09','06:30','ESTACA','PRESIDENCIA DA ESTACA E SUMO CONSELHO');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','CONSELHO DE BISPOS','2022/10/15','','ESTACA','PRESIDENCIA DE ESTACA E BISPADOS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','TREINAMENTO PARA NOVOS LIDERES','2022/10/16','','ESTACA','');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE PRESIDENCIA DE ESTACA','2022/10/19','19:30','ESTACA','PRESIDENCIA DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE SUMO CONSELHO','2022/10/23','06:30','ESTACA','PRESIDENCIA DA ESTACA E SUMO CONSELHO');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','CONFERENCIA ALA UNIVERSITARIO','2022/10/30','SACRAMENTAL DA ALA','CAPELA UNIVER.','MEMBROS DA ALA E CONVIDADOS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','CONSELHO DE ESTACA','2022/10/30','','ESTACA','PRESIDENCIA DE ESTACA E LIDERES DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE PRESIDENCIA DA ESTACA','2022/11/02','19:30','ESTACA','PRESIDENCIA DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE SUMO CONSELHO','2022/11/06','06:30','ESTACA','PRESIDENCIA DA ESTACA E SUMO CONSELHO');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','CONFERENCIA DE ESTACA / CONSELHO ESTACA','2022/11/12','16:00','ESTACA','LIDERES DA ESTACA E ALAS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','CONFERENCIA DE ESTACA / SESSAO DE ADULTOS','2022/11/12','18:00','ESTACA','TODOS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','CONFERENCIA DE ESTACA / SESSAO GERAL','2022/11/13','10:00','ESTACA','TODOS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE PRESIDENCIA DA ESTACA','2022/11/16','19:30','ESTACA','PRESIDENCIA DA ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','COMUNICAÇAO','RESERVADO','2022/11/19','','','');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE SUMO CONSELHO','2022/11/20','06:30','ESTACA','PRESIDENCIA DA ESTACA E SUMO CONSELHO');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','HISTORIA DA FAMILIA','DEVOCIONAL.HOSTORIA DA FAMILIA','2022/11/20','18:00','ESTACA','TODOS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','OM','CONFRA DAS LIDERES','2022/11/26','','ESTACA','LEDERES DAS MOCAS');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','BEM ESTAR E AUTOSUFICIENCIA','TREINAMENTO NACIONAIS DOS ESPECIALISTAS','2022/11/27','','','');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE PRESIDENCIA DA ESTACA','2022/11/30','19:30','ESTACA','PRESIDENCIA DE ESTACA');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE SUMO CONSELHO','2022/12/04','06:30','ESTACA','PRESIDENCIA DA ESTACA E SUMO CONSELHO');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE PRESIDENCIA DA ESTACA','2022/12/14','19:30','ESTACA','PRESIDENCIA DA ESTACA ');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','REUNIAO DE SUMO CONSELHO','2022/12/18','06:30','ESTACA','PRESIDENCIA DA ESTACA E SUMO CONSELHO');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ORM','SABADOOH','2022/12/24','','ESTACA','JOVENS E LIDERES');
INSERT INTO calendars (stake, organizacao, evento, data, horario, local, publico) VALUES ('Maceió Tabuleiro','ESTACA','PRESIDENCIA DA ESTACA','2022/12/28','19:30','ESTACA','PRESIDENCIA DA ESTACA');

